services:
  telegram-bot:
    build: .
    container_name: ptb-mn
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
      - ./logs:/bot/logs
    environment:
      CONTAINER: "true"