services:
  bot:
    build: .
    container_name: ptb-mn
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - ./bot:/bot
    environment:
      CONTAINER: "true"
